DROP TABLE IF EXISTS "card";
DROP TABLE IF EXISTS "cardmove";
DROP TABLE IF EXISTS "turn";
DROP TABLE IF EXISTS "result";
DROP TABLE IF EXISTS "league";
DROP TABLE IF EXISTS "player";
DROP TABLE IF EXISTS "game";
DROP TABLE IF EXISTS "visitor";