@startuml src/main/resources/plantuml/Casino.png
		skinparam classAttributeIconSize 0
		package "nl.deknik.card" {
		package "entity" {

enum AiLevel {
DUMB
MEDIUM
SMART
..
HUMAN
NONE
}

class Player {
- playerId : int
- created : String
..
- alias : String
- human : boolean
- cubits : int
- playingOrder : int
- securedLoan : int
--
+ makeHuman(in: boolean)
}
Player "1" -right- "0..n" Turn
Player -left- AiLevel

class Turn {
- turnId : int
- created : String
..
- round : int
- turn : int
- playerId : int
- cardAction : CardAction
- bet : int
--
+ increaseCurrentRound()
+ increaseCurrentTurn()

}
Turn "1" -right- "0..n" Cards : plays
Turn "1" -up- "0..n" Game : plays
Turn -down- CardAction

class Cards {
- cardId : int
- created : String
..
- cardName : String
- roundSequence : int
- turnSequence : int
- cardOrder : int
- cardLocation : CardLocation
...
+ startWithShuffledDeck(in: #jokers)
}
Cards -down- CardLocation

class Card {
- Rank rank
- Suit suit
+ compareTo()
}

enum CardLocation {
DECK
DRAW_PILE
HAND
TABLE
DISCARD_PILE
}
enum CardAction {
DEAL
HIGHER
LOWER
PASS
NEXT
}

class Game {
+ cardGameId : int
- created : String
..
- state : int
- ante : int
- activeTurn : int
}
Game -up- Type
Game -up- Variant
Game "1" -right- "0..n" PlayedCards : history

enum Type {
HIGHLOW
BLACKJACK
}

enum Variant {
	variantAnte;
	variantBetting;
	variantDeck;
	variantInsurance;
	variantRound;
	variantTurns;
}

class PlayedCards {
- copyOfCards
..
}
@enduml