package cloud.qasino.card.database.configuration;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Getter
@Setter
@ConfigurationProperties(prefix = "param.service.database")
public class DatabaseProperties {

    private String jdbcUrl;
    private String username;
    private String password;
    private String driverClassName = "oracle.jdbc.OracleDriver";
    //datasource properties configurations
    private int prepStmtCacheSize = 10;
    private String poolName; // will be autogenerated
    private int connectionTimeout = 10000;
    private int maxLifetime = 30000;
    private int maximumPoolSize = 10;
    private int minimumIdle = 10; //should be the same as pool size
    private int idleTimeout = 10000;
}
